### ISSUE TITLE
Lifted tuple accessors

### ISSUE THREAD

**Issue by duairc** [ulricha/dsh#2]
In `Database.DSH`, there's a GADT `TupElem` with constructors like `Tup3_1`, `Tup3_2` and so on. Their intent seems to be to help implement lifted tuple accessors, e.g.:

```
tup3_1 :: (QA a, QA b, QA c) => Q (a, b, c) -> Q a
```

However, no such functions seem to be exported anywhere in `DSH`. It would be nice if they were. I could submit a pull request but i'm not sure what module such functions should be in, and given that `Tup3_1`, `Tup3_2` and so on seem to be generated with Template Haskell, maybe you would want to generate `tup3_1` and `tup3_2` with Template Haskell too.

**Comment by ulricha** [comment]
I just added lifted tuple accessors, generated via TH. This has been on my TODO list for a while, thanks for pushing it to the top.

``` haskell
*> import qualified Database.DSH as Q
*> import Database.DSH.Compiler
*> showComprehensionsQ $ Q.map Q.tup3_2 $ Q.toQ ([(1,2,3)] :: [(Integer, Integer, Integer)])
--------------------------------------------------------------------------------
[ v1.2 | v1 <- sng (( 1, 2, 3 )) ]
--------------------------------------------------------------------------------
```

Note that you can also use view patterns to match on tuples:

``` haskell
*> :set -XViewPatterns
*> showComprehensionsQ $ Q.map (\(Q.view -> (_, b, _)) -> b) $ Q.toQ ([(1,2,3)] :: [(Integer, Integer, Integer)])
--------------------------------------------------------------------------------
[ v1.2 | v1 <- sng (( 1, 2, 3 )) ]
--------------------------------------------------------------------------------
```

**Comment by duairc** [comment]
Great, thanks for the quick response. And I didn't know about the view patterns, I'll look into them. Thanks!

**Comment by ulricha** [comment]
Admittedly, documentation is rather inadequate. The best way is probably to go through the examples in https://github.com/ulricha/dsh-example-queries.
