### ISSUE TITLE
Examples don't compile

### ISSUE THREAD

**Issue by jstolarek** [ulricha/dsh#6]
After finally managing to compile and install DSH (see #5) I cannot get examples to run. There are missing imports (`Database.DSH.Backend`, `Database.HDBC.Types`) but once these are sorted there are missing functions (`disconnect`) and instances (`Database.DSH.Backend.Backend Connection`). I managed to solve the former but not the latter.

**Comment by ulricha** [comment]
Examples in `DSH/examples` are outdated. Please consider examples in https://github.com/dsh-example-queries/.
